name = "atlas"
output_path = "../"
output_type = "Json"
folders = [
    "variants",
    "chest"
]

[image_options]
output_extension = "Png"
max_size = 4096
show_extension = false

[features]
nine_patch = false
